DATASETS:
  NAME: "CIFAR100"
  # SEED: 42 (unused)
  DATA_AUGMENTATION: "STANDARD"
  CIFAR:
    SHUFFLE_INDICES: False
    TRAIN_INDICES: [0, 45000,]
    VALID_INDICES: [45000, 50000,]

MODEL:
  META_ARCHITECTURE:
    NAME: "ImageClassificationModelBase"
  PIXEL_MEAN: [0.5072, 0.4866, 0.4410,]
  PIXEL_STD: [0.2673, 0.2564, 0.2760,]
  BACKBONE:
    NAME: "VGGNet"
    VGGNET:
      DEPTH: 19
      IN_PLANES: 64
      MLP_HIDDENS: []
      CONV_LAYERS: "Conv2d"
      NORM_LAYERS: "NONE"
      ACTIVATIONS: "ReLU"
      LINEAR_LAYERS: "Linear"
  CLASSIFIER:
    NAME: "SoftmaxClassifier"
    SOFTMAX_CLASSIFIER:
      NUM_CLASSES: 100
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear"
