DATASETS:
  NAME: "CIFAR10"
  # SEED: 42 (unused)
  DATA_AUGMENTATION: "STANDARD"
  CIFAR:
    SHUFFLE_INDICES: False
    TRAIN_INDICES: [0, 45000,]
    VALID_INDICES: [45000, 50000,]

MODEL:
  META_ARCHITECTURE:
    NAME: "ImageClassificationModelBase"
  PIXEL_MEAN: [0.4915, 0.4821, 0.4464,]
  PIXEL_STD: [0.2472, 0.2437, 0.2617,]
  BACKBONE:
    NAME: "VGGNet"
    VGGNET:
      DEPTH: 13
      IN_PLANES: 64
      MLP_HIDDENS: []
      CONV_LAYERS: "Conv2d"
      NORM_LAYERS: "NONE"
      ACTIVATIONS: "ReLU"
      LINEAR_LAYERS: "Linear"
  CLASSIFIER:
    NAME: "SoftmaxClassifier"
    SOFTMAX_CLASSIFIER:
      NUM_CLASSES: 10
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear"
