DATASETS:
  NAME: "ImageNet1k_x32"
  SEED: 42
  DATA_AUGMENTATION: "STANDARD"
  DOWNSAMPLED_IMAGENET:
    SHUFFLE_INDICES: True
    TRAIN_INDICES: [0, 1231167,]
    VALID_INDICES: [1231167, 1281167,]

MODEL:
  META_ARCHITECTURE:
    NAME: "ImageClassificationModelBase"
  PIXEL_MEAN: [0.485, 0.456, 0.406,]
  PIXEL_STD: [0.229, 0.224, 0.225,]
  BACKBONE:
    NAME: "VGGNet"
    VGGNET:
      DEPTH: 16
      IN_PLANES: 64
      MLP_HIDDENS: [512, 512,]
      CONV_LAYERS: "Conv2d"
      NORM_LAYERS: "NONE"
      ACTIVATIONS: "ReLU"
      LINEAR_LAYERS: "Linear"
  CLASSIFIER:
    NAME: "SoftmaxClassifier"
    SOFTMAX_CLASSIFIER:
      NUM_CLASSES: 1000
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear"
